stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE_NAME: web-scio
  DOCKER_IMAGE_TAG: $CI_COMMIT_SHORT_SHA
  CONTAINER_NAME: web-scio

# Use Docker in Docker service
services:
  - docker:dind

build:
  stage: build
  image: docker:stable
  script:
    - docker build -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG .
    - docker save $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG > image.tar
  artifacts:
    paths:
      - image.tar
    expire_in: 1 hour

deploy_staging:
  stage: deploy
  image: docker:stable
  only:
    - main  # Only deploy when changes are pushed to main branch
  script:
    - docker load < image.tar
    # Stop and remove existing container if it exists
    - docker stop $CONTAINER_NAME || true
    - docker rm $CONTAINER_NAME || true
    # Start new container with the built image
    - >
      docker run -d
      --name $CONTAINER_NAME
      -p 5173:5173
      -v $(pwd)/src:/app/src
      -v /app/node_modules
      --restart unless-stopped
      $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
  tags:
    - shell  # Make sure this runner has shell executor