services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3001
    command: npm run dev -- --host 0.0.0.0

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - PORT=3001
      - NODE_ENV=development
      - USE_TEST_EMAIL=true
      - SEND_CONFIRMATION=true
      - ALLOWED_ORIGINS=http://localhost:5173
      - COMPANY_NAME=Corporación Scio
    command: npm run dev